# Generated by Django 5.1.2 on 2024-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
