# Generated by Django 5.1.2 on 2024-11-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_custom_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='is_staff',
        ),
    ]
