# Generated by Django 5.1.2 on 2024-10-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_name_user_username_alter_user_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
