# Generated by Django 5.1.2 on 2024-10-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='num',
        ),
    ]
