# Generated by Django 5.1.2 on 2024-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_number_user_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
